import { Toaster } from "sonner";
import { Provider } from "jotai";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next";

import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const notoSans = Noto_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable}  antialiased`}>
        <TRPCReactProvider>
          <NuqsAdapter>
            <Provider>{children}</Provider>
          </NuqsAdapter>
        </TRPCReactProvider>
        <Toaster closeButton />
      </body>
    </html>
  );
}
